project:
  type: website
  output-dir: docs

website:
  title: "Daniel Yeom"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Research projects
      - href: media.qmd
        text: Media

format:
  html:
    theme:
      dark: [solar, theme-dark.scss]
      light: cosmo
    css: styles.css
    toc: false

editor: visual



